name: atomkit
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python>=3.10,<3.14
  
  # Core scientific computing
  - numpy>=1.24.0,<3.0.0
  - pandas>=2.2.0,<3.0.0
  - scipy>=1.10.0,<2.0.0
  
  # Atomic physics data
  - pip
  
  # Plotting (optional but recommended)
  - matplotlib>=3.7.0,<4.0.0
  - seaborn>=0.12.0,<0.14.0
  
  # Utilities
  - colorama>=0.4.6,<0.5.0
  - tabulate>=0.9.0,<0.10.0
  
  # Development tools
  - pytest>=7.4.0,<9.0.0
  - pytest-cov>=4.0.0,<6.0.0
  
  # Code quality
  - black>=23.0.0,<25.0.0
  - ruff>=0.1.0,<1.0.0
  
  # Pip dependencies (not available in conda)
  - pip:
    - mendeleev>=0.9.0,<2.0.0
    - colorlog>=6.7.0,<7.0.0
    - roman>=5.0.0,<6.0.0
